### PR TITLE
Added multi-cell select, CSS Color Settings, and minor CSS changes

### PR DESCRIPTION
**Pull request by y-haidar**
## Motivation

Addresses: #4 
EDIT: Addresses: #1 

### Testing

I have been manually using it for a couple of days now, and did not notice any UI breaking bugs.

### Additional notes

- When cell is one line, the added `Icon` can look off center
- Color selections may not be the best. Was not tested on light theme
- Not tested on Notebook(only lab)

### CODE REVIEW

**Review by CarlosDominguezBecerril — COMMENTED** [review]
Thanks for your work! I tested it and works as expected.

About the CSS change, do you have a picture / video showing the issue of the icon being off center? I'm unable to reproduce it

**Comment by y-haidar** [comment]
I guess my choice of words weren't the best. I meant that it is not aligned with the output number. In the case of this image `[45]:`. It has nothing to do with "centering".

image

Maybe the `1.5em` padding is not the best for the upper side.

This image below with the following padding:

```
padding-top: 1em;
padding-left: 1.2em;
```

image

Forgive me, as I am not good with design.

**Comment by CarlosDominguezBecerril** [comment]
Hey! No problem I'm also bad with design.

using this looks indeed better!
```
padding-top: 1em;
padding-left: 1.2em;
```

What do you think about increasing opacity to a higher value? This is 0.3 vs 1

Screenshot 2024-10-18 at 15 13 17

What about changing z-indez to 0 so that we can see always the icon?

Screenshot 2024-10-18 at 15 16 40

**Comment by y-haidar** [comment]
If we remove the opacity then the highlight from the selection would be hard see.

Without selecting cells             |  Selecting three cells
:-------------------------:|:-------------------------:
Without selecting cells |  Selecting three cells

I did remove the `z-index` it looked fine without it, not sure why I had it.

**Comment by CarlosDominguezBecerril** [comment]
Okay! Thanks for the info. What do you think about changing opacity to around 0.5? Leaving those two changes in the PR to you and then we can merge and release

**Review by CarlosDominguezBecerril — APPROVED** [review]
LGTM! Thanks a lot for the change 😄 . I will try to cut a new release tomorrow or Wednesday

**Review by CarlosDominguezBecerril — APPROVED** [review]
Do you mind updating the title and description to ensure it matches what we are fixing in the PR? Thanks!

**Comment by y-haidar** [comment]
Sorry, I am new to the github workflow, it didn't cross my mind that I was supposed to create a new branch in order to not affect this PR. I can revert the changes and fine with squash commit, if you would like.

**Comment by CarlosDominguezBecerril** [comment]
That's okay! Ideally, once a PR is approved, you don't want to add new features to avoid changing its scope. Creating a new branch for additional features helps maintain clarity and manageability

**Comment by CarlosDominguezBecerril** [comment]
I will release a new version tomorrow 👍

**Pull request merged**
